config/routes.rb
Rails.application.routes.draw do
  #comment
  resources :comments
  get 'login/index'
  resources :registers
  resources :reports
  resources :events do
    member do
      post "vote"#, to: "events#upvote"
      post "downvote"#, to: "events#downvote"
    end
    resources :comments
  end
  resources :users
  resources :home
  
  #root 'users#index'
  #root 'events#index'
  #root 'reports#index'
  #root 'static_pages#homepage'
  root 'events#index'
  #root 'registers#index'
  get 'static' => 'static_pages#static'
  get 'howto' => 'static_pages#howto'
  get  'about' => 'static_pages#about'
  get  'contact'  => 'static_pages#contact'
  get  'homepage'  => 'static_pages#homepage'
  #get 'users/index'
  get 'events/index'
  #get 'reports/index'
  #get 'login/index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'registers#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'homeevent', to: 'static_pages#homepage', as: 'homeevent'
  get 'back', to: 'static_pages#static', as: 'back'
  get 'account', to: 'home#index', as: 'account'
  get '/search' => 'events#search', :as => 'search_page'
end

app/models/event.rb
class Event < ApplicationRecord
    validates :title, presence: true
    validates :category, presence: true
    validates :description, presence: true
    validates :phone, presence: true 
    belongs_to :register
    acts_as_votable
    has_many :comments
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [ :edit, :update, :destroy,:new,:create ,:show]
  # GET /events
  # GET /events.json
  def index
    @events = Event.all.order("created_at DESC")
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @events = Event.all
  end

  # GET /events/new
  def new
    @event = current_register.events.new
  end

  # GET /events/1/edit
  def edit
    @event.register = current_register
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_register.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  def search
    if params[:search].blank?  
      redirect_to(root_path, alert: "Empty field!") and return  
    else  
      @parameter = params[:search].downcase  
      @results = Event.all.where("lower(category) LIKE :search", search: @parameter)  
    end  
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def vote
    @event = Event.find(params[:id])
    @event.upvote_by current_register
    redirect_back fallback_location: root_path
  end
    
  def downvote
    @event = Event.find(params[:id])
    @event.downvote_by current_register
    redirect_back fallback_location: root_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :category, :description, :by ,:start, :end, :phone)
    end
    
   

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<!DOCTYPE html>
<html>
    <head>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
      /*the container must be positioned relative:*/
      .custom-select {
        position: relative;
        font-family: Arial;
      }
      
      .custom-select select {
        display: none; /*hide original SELECT element:*/
      }
      
      .select-selected {
        background-color: #f6f6f6;
      }
      
      /*style the arrow inside the select element:*/
      .select-selected:after {
        position: absolute;
        content: "";
        top: 14px;
        right: 10px;
        width: 0;
        height: 0;
        border-color: #fff transparent transparent transparent;
      }
      
      /*point the arrow upwards when the select box is open (active):*/
      .select-selected.select-arrow-active:after {
        border-color: transparent transparent #fff transparent;
        top: 7px;
        
      }
      
      /*style the items (options), including the selected item:*/
      .select-items div,.select-selected {
          color: #0d0d0d;
          padding: 8px 16px;
          border: 1px solid transparent;
          border-color: transparent transparent rgba(0, 0, 0, 0.1) transparent;
          cursor: pointer;
          user-select: none;
          padding: 15px 32px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
          font-size: 16px;
          margin: 5px;
          width: 85%;
          border: 2px solid #f6f6f6;
          -webkit-transition: all 0.5s ease-in-out;
          -moz-transition: all 0.5s ease-in-out;
          -ms-transition: all 0.5s ease-in-out;
          -o-transition: all 0.5s ease-in-out;
          transition: all 0.5s ease-in-out;
          -webkit-border-radius: 5px 5px 5px 5px;
          border-radius: 5px 5px 5px 5px;
      }
      
      /*style items (options):*/
      .select-items {
        position: absolute;
        background-color: #f6f6f6;
        top: 100%;
        left: 0;
        right: 0;
        z-index: 99;
      }
      
      /*hide the items when the select box is closed:*/
      .select-hide {
        display: none;
      }
      
      .select-items div:hover, .same-as-selected {
        background-color: rgba(0, 0, 0, 0.1);
      }
      .datetime select:nth-child(1) {
          width: 130px;
          text-indent: 15px; 
}
      </style>
    </head>     

    <body>
      
        <div class="wrapper2 ">
        <p id="alert"><%= alert %></p>
          <div id="formContent">
            <!-- Tabs Titles -->
            <h2 class="active">CREATE an EVENT </h2>
              <%= form_for @event do |f| %>
                <% if @event.errors.any? %>
                  <div id="error_explanation">
                    <h2>
                      <%= "#{pluralize(@event.errors.count, "error")} prohibited this register from being saved:" %>
                    </h2>
                    <ul>
                      <% @event.errors.full_messages.each do |message| %>
                        <li>
                          <%= message %>
                        </li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
                            <!--surround the select box with a "custom-select" DIV element. Remember to set the width:-->
        
              <div>
                  <%= f.text_field :title, required: true, placeholder: "Title" %>
              </div>
              <div  style="width:100%; color: #cccccc;">
                <div class="custom-select">
                     <%= f.select :category,['food','concert','movie','sport','travel','game','university','Etc'] %>
                </div>
              </div>
              <div>
                  <%= f.text_field :description, required: true,placeholder: "Desciption"  %>
              </div>
              <div>
                  <%= f.text_field :by, required: true, placeholder: "by" %>
              </div>
              <div >
                <%= f.date_select :start , maxlength: 500, size: 15,rows: 10, cols: 25 ,width:100 %>
              </div>
              <div >
                <%= f.date_select :end , maxlength: 500, size: 15,rows: 10, cols: 25,width:100 %>
              </div>
              <div >
                <%= f.text_field :phone , maxlength: 500, size: 15,rows: 10, cols: 25,width:100 %>
              </div>
              <br>
              <table width=100%>
                  <tr>
                      <th>
                        <div class="actions" style="text-align:center">
                         <%= submit_tag "SAVE" %> 
                        </div>
                      </th>
                  </tr>
              </table>
            <% end %>
            </div>
          </div>
        
          <script>
          var x, i, j, selElmnt, a, b, c;
          /*look for any elements with the class "custom-select":*/
          x = document.getElementsByClassName("custom-select");
          for (i = 0; i < x.length; i++) {
            selElmnt = x[i].getElementsByTagName("select")[0];
            /*for each element, create a new DIV that will act as the selected item:*/
            a = document.createElement("DIV");
            a.setAttribute("class", "select-selected");
            a.innerHTML = selElmnt.options[selElmnt.selectedIndex].innerHTML;
            x[i].appendChild(a);
            /*for each element, create a new DIV that will contain the option list:*/
            b = document.createElement("DIV");
            b.setAttribute("class", "select-items select-hide");
            for (j = 1; j < selElmnt.length; j++) {
              /*for each option in the original select element,
              create a new DIV that will act as an option item:*/
              c = document.createElement("DIV");
              c.innerHTML = selElmnt.options[j].innerHTML;
              c.addEventListener("click", function(e) {
                  /*when an item is clicked, update the original select box,
                  and the selected item:*/
                  var y, i, k, s, h;
                  s = this.parentNode.parentNode.getElementsByTagName("select")[0];
                  h = this.parentNode.previousSibling;
                  for (i = 0; i < s.length; i++) {
                    if (s.options[i].innerHTML == this.innerHTML) {
                      s.selectedIndex = i;
                      h.innerHTML = this.innerHTML;
                      y = this.parentNode.getElementsByClassName("same-as-selected");
                      for (k = 0; k < y.length; k++) {
                        y[k].removeAttribute("class");
                      }
                      this.setAttribute("class", "same-as-selected");
                      break;
                    }
                  }
                  h.click();
              });
              b.appendChild(c);
            }
            x[i].appendChild(b);
            a.addEventListener("click", function(e) {
                /*when the select box is clicked, close any other select boxes,
                and open/close the current select box:*/
                e.stopPropagation();
                closeAllSelect(this);
                this.nextSibling.classList.toggle("select-hide");
                this.classList.toggle("select-arrow-active");
              });
          }
          function closeAllSelect(elmnt) {
            /*a function that will close all select boxes in the document,
            except the current select box:*/
            var x, y, i, arrNo = [];
            x = document.getElementsByClassName("select-items");
            y = document.getElementsByClassName("select-selected");
            for (i = 0; i < y.length; i++) {
              if (elmnt == y[i]) {
                arrNo.push(i)
              } else {
                y[i].classList.remove("select-arrow-active");
              }
            }
            for (i = 0; i < x.length; i++) {
              if (arrNo.indexOf(i)) {
                x[i].classList.add("select-hide");
              }
            }
          }
          /*if the user clicks anywhere outside the select box,
          then close all select boxes:*/
          document.addEventListener("click", closeAllSelect);
          </script>
    </body>
</html>

app/views/events/edit.html.erb
<!DOCTYPE html>
<html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
      /*the container must be positioned relative:*/
      .custom-select {
        position: relative;
        font-family: Arial;
      }
      
      .custom-select select {
        display: none; /*hide original SELECT element:*/
      }
      
      .select-selected {
        background-color: #f6f6f6;
      }
      
      /*style the arrow inside the select element:*/
      .select-selected:after {
        position: absolute;
        content: "";
        top: 14px;
        right: 10px;
        width: 0;
        height: 0;
        border-color: #fff transparent transparent transparent;
      }
      
      /*point the arrow upwards when the select box is open (active):*/
      .select-selected.select-arrow-active:after {
        border-color: transparent transparent #fff transparent;
        top: 7px;
        
      }
      
      /*style the items (options), including the selected item:*/
      .select-items div,.select-selected {
        color: #0d0d0d;
        padding: 8px 16px;
        border: 1px solid transparent;
        border-color: transparent transparent rgba(0, 0, 0, 0.1) transparent;
        cursor: pointer;
        user-select: none;

          padding: 15px 32px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
          font-size: 16px;
          margin: 5px;
          width: 85%;
          border: 2px solid #f6f6f6;
          -webkit-transition: all 0.5s ease-in-out;
          -moz-transition: all 0.5s ease-in-out;
          -ms-transition: all 0.5s ease-in-out;
          -o-transition: all 0.5s ease-in-out;
          transition: all 0.5s ease-in-out;
          -webkit-border-radius: 5px 5px 5px 5px;
          border-radius: 5px 5px 5px 5px;
      }
      
      /*style items (options):*/
      .select-items {
        position: absolute;
        background-color: #f6f6f6;
        top: 100%;
        left: 0;
        right: 0;
        z-index: 99;
      }
      
      /*hide the items when the select box is closed:*/
      .select-hide {
        display: none;
      }
      
      .select-items div:hover, .same-as-selected {
        background-color: rgba(0, 0, 0, 0.1);
      }
      .datetime select:nth-child(1) {
          width: 130px;
          text-indent: 15px; 
}
      </style>
    </head>     

    <body>
      
        <div class="wrapper2 ">
        <p id="alert"><%= alert %></p>
          <div id="formContent">
            <!-- Tabs Titles -->
            <h2 class="active">edit an EVENT </h2>
        
            <%= form_for @event do |f| %>
              <% if @event.errors.any? %>
                <div id="error_explanation">
                  <h2>
                    <%= "#{pluralize(@event.errors.count, "error")} prohibited this register from being saved:" %>
                  </h2>
                  <ul>
                    <% @event.errors.full_messages.each do |message| %>
                      <li>
                        <%= message %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
                            <!--surround the select box with a "custom-select" DIV element. Remember to set the width:-->
        
              <div class="  field">
                  <%= f.text_field :title, required: true, placeholder: "Title" %>
              </div>
              <div class=" " style="width:100%; color: #cccccc;">
                <div class="custom-select">
                     <%= f.select :category,['food','concert','movie','sport','travel','game','university','Etc.']%>
                </div>
               
              </div>
              <div class="  " >
                  <%= f.text_field :description, required: true, placeholder: "Description" %>
              </div>
              <div class="  field">
                  <%= f.text_field :by, required: true, placeholder: "BY" %>
              </div>
              <div class="  field">
                <%= f.date_select :start , maxlength: 500, size: 15,rows: 10, cols: 25, placeholder: "Start",width:100 %>
              </div>
              <div class="  field">
                <%= f.date_select :end , maxlength: 500, size: 15,rows: 10, cols: 25, placeholder: "End",width:100 %>
              </div>
              <div class=" field">
                <%= f.text_field :phone , maxlength: 500, size: 15,rows: 10, cols: 25, placeholder: "Phone",width:100 %>
              </div>
              
              <br>
              <table width=100%>
                  <tr>
                      <th><div class="actions" style="text-align:center"><%= submit_tag "SAVE" %> </div></th>
                  </tr>
                  <tr>
                      <th><div class="" style="text-align:center;font-family: 'Quicksand', sans-serif, sans-serif;font-size: 28px;"><%= link_to "cencel", root_path %> </div></th>
                  </tr>
                
              </table>
              
            <% end %>
          </div>
        </div>
        
        <script>
        var x, i, j, selElmnt, a, b, c;
        /*look for any elements with the class "custom-select":*/
        x = document.getElementsByClassName("custom-select");
        for (i = 0; i < x.length; i++) {
          selElmnt = x[i].getElementsByTagName("select")[0];
          /*for each element, create a new DIV that will act as the selected item:*/
          a = document.createElement("DIV");
          a.setAttribute("class", "select-selected");
          a.innerHTML = selElmnt.options[selElmnt.selectedIndex].innerHTML;
          x[i].appendChild(a);
          /*for each element, create a new DIV that will contain the option list:*/
          b = document.createElement("DIV");
          b.setAttribute("class", "select-items select-hide");
          for (j = 1; j < selElmnt.length; j++) {
            /*for each option in the original select element,
            create a new DIV that will act as an option item:*/
            c = document.createElement("DIV");
            c.innerHTML = selElmnt.options[j].innerHTML;
            c.addEventListener("click", function(e) {
                /*when an item is clicked, update the original select box,
                and the selected item:*/
                var y, i, k, s, h;
                s = this.parentNode.parentNode.getElementsByTagName("select")[0];
                h = this.parentNode.previousSibling;
                for (i = 0; i < s.length; i++) {
                  if (s.options[i].innerHTML == this.innerHTML) {
                    s.selectedIndex = i;
                    h.innerHTML = this.innerHTML;
                    y = this.parentNode.getElementsByClassName("same-as-selected");
                    for (k = 0; k < y.length; k++) {
                      y[k].removeAttribute("class");
                    }
                    this.setAttribute("class", "same-as-selected");
                    break;
                  }
                }
                h.click();
            });
            b.appendChild(c);
          }
          x[i].appendChild(b);
          a.addEventListener("click", function(e) {
              /*when the select box is clicked, close any other select boxes,
              and open/close the current select box:*/
              e.stopPropagation();
              closeAllSelect(this);
              this.nextSibling.classList.toggle("select-hide");
              this.classList.toggle("select-arrow-active");
            });
        }
        function closeAllSelect(elmnt) {
          /*a function that will close all select boxes in the document,
          except the current select box:*/
          var x, y, i, arrNo = [];
          x = document.getElementsByClassName("select-items");
          y = document.getElementsByClassName("select-selected");
          for (i = 0; i < y.length; i++) {
            if (elmnt == y[i]) {
              arrNo.push(i)
            } else {
              y[i].classList.remove("select-arrow-active");
            }
          }
          for (i = 0; i < x.length; i++) {
            if (arrNo.indexOf(i)) {
              x[i].classList.add("select-hide");
            }
          }
        }
        /*if the user clicks anywhere outside the select box,
        then close all select boxes:*/
        document.addEventListener("click", closeAllSelect);
        </script>
    
    </body>
    </html>

app/views/events/index.html.erb
<html>
  <head>
    <title>I'm in</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <% @events.each do |event| %>
        <div class="link row clearfix font">
          <table>
              <tr >
                <th><h2 id="h5"><%= link_to event.title, event %>&nbsp&nbsp&nbsp&nbsp<p id="h4"># <%= event.category %> </p></h2></th><br>
              </tr>
              
              <tr>
                <th><h3><small class="author">&nbsp&nbspSubmitted &nbsp<%= time_ago_in_words(event.created_at) %>&nbsp by <%= event.register.username %> &nbsp</small></h3></th>
              </tr>
          </table>
        </div>
    <% end %>
  </body>
</html>

app/views/events/new.html.haml
= render 'form'

app/views/events/search.html.erb
<html>
<body>

    
    <h3>Search Result</h3>  

    <% @results.each do |result| %>
        <%= link_to result.title,result %><br>
         
    <% end %>
        
</body>
</html>

app/views/events/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>imin</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
      <div class="box">
            <p id="notice">
              <%= notice %>
            </p>
           <span>
              <p class="th1" style="font-size:20px;font-weight:60;color:#3b15d4">
              <%= @event.title %></p>
              <p class="th1"  style="font-size:20px;font-weight:60;color:#3b15d4">#<%= @event.category %></p>
           </span>
            <p class="th1">
              <div id="box2">
                <span><%= @event.description %></span>
              </div>
            </p>
              <table width=100%>
                  <tr class="th1">
                      <th>
                          <p >&nbsp&nbsp&nbsp&nbsp</p>
                      </th>
                     <th>
                          <p >&nbsp&nbsp&nbsp&nbsp</p>
                      </th>
                </tr>
                <tr class="th1">
                  <th>
                      <p class="th2"style="font-size:16px;font-weight:100;"><b>By&nbsp&nbsp&nbsp&nbsp</b><%= @event.register.username %></p>
                  </th>
                  <th>
                      <p  class="th2"style="font-size:16px;font-weight:100;"><b>Phone&nbsp&nbsp&nbsp&nbsp</b><%= @event.phone %> </p>
                  </th>
                </tr>
                <tr class="th2">
                  <th>
                      <p  class="th2"style="font-size:16px;font-weight:100;"><b>Start&nbsp&nbsp&nbsp&nbsp</b><%= @event.start %> </p>
                  </th>
                  <th>
                      <p  class="th2"style="font-size:16px;font-weight:100;"><b>End&nbsp&nbsp&nbsp&nbsp</b><%= @event.end %> </p>
                  </th>
                </tr>
              <h2>
               
                
                <tr class="th2">
                  <th>
                      <p>&nbsp</p>
                  </th>
                 <% if  %>
                       <th style="text-align:right">
                                <%= link_to vote_event_path(@event), method: :post do %>
                                  <button>Upvote</button>
                                  <%= @event.get_upvotes.size %>
                                  <% end %>
                                <%= link_to downvote_event_path(@event), method: :post do %>
                                  <button>Downvote</button>
                                  <%= @event.get_downvotes.size   %>
                                  <% end %>&nbsp&nbsp&nbsp
                                <% if @event.register == current_register %> 
                                  <%= link_to 'Edit', edit_event_path(@event) %>&nbsp&nbsp&nbsp
                                  <%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' } %>
                                <% end %>
                       </th>
                  <% else %>
                        <th>
                              <p>&nbsp</p>
                        </th>
                  <% end %>
                </tr>
                <br/>
              </table>
       </div>
       <div>
         <br><br>
       </div>
       <div class="box">
         <h3> <%= @event.comments.count %>  comments   </h3>
                <%= render :partial => @event.comments %>
                <%= simple_form_for [@event, Comment.new] do |f| %>
                  <table id="box3">
                      <%= f.text_area :body %>
                      <%= f.submit "Add comment" %>  
                  </table>
                  
                <% end %>
             
       </div>
</body>
</html>