config/routes.rb
Rails.application.routes.draw do
  #comment
  resources :comments
  get 'login/index'
  resources :registers
  resources :reports
  resources :events do
    member do
      post "vote"#, to: "events#upvote"
      post "downvote"#, to: "events#downvote"
    end
    resources :comments
  end
  resources :users
  resources :home
  
  #root 'users#index'
  #root 'events#index'
  #root 'reports#index'
  #root 'static_pages#homepage'
  root 'events#index'
  #root 'registers#index'
  get 'static' => 'static_pages#static'
  get 'howto' => 'static_pages#howto'
  get  'about' => 'static_pages#about'
  get  'contact'  => 'static_pages#contact'
  get  'homepage'  => 'static_pages#homepage'
  #get 'users/index'
  get 'events/index'
  #get 'reports/index'
  #get 'login/index'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'registers#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'homeevent', to: 'static_pages#homepage', as: 'homeevent'
  get 'back', to: 'static_pages#static', as: 'back'
  get 'account', to: 'home#index', as: 'account'
  get '/search' => 'events#search', :as => 'search_page'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :register
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    validates :title, presence: true
    validates :category, presence: true
    validates :description, presence: true
    validates :phone, presence: true 
    belongs_to :register
    acts_as_votable
    has_many :comments
    
end

app/models/register.rb
class Register < ApplicationRecord
    has_secure_password
    validates :email, uniqueness: true,format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
    validates :password, presence: true
    validates :password_confirmation, presence: true
    validates :username, uniqueness: true
    validates :phone, presence: true , format: { with: /\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})/ } 
    mount_uploader :image, ImageUploader 
    has_many :events
end

app/models/report.rb
class Report < ApplicationRecord
     validates :event, presence: true
     validates :report_to, presence: true
     validates :by, presence: true
     validates :desciption, presence: true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [ :edit, :update, :destroy,:new,:create ,:show]
  # GET /events
  # GET /events.json
  def index
    @events = Event.all.order("created_at DESC")
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @events = Event.all
  end

  # GET /events/new
  def new
    @event = current_register.events.new
  end

  # GET /events/1/edit
  def edit
    @event.register = current_register
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_register.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  def search
    if params[:search].blank?  
      redirect_to(root_path, alert: "Empty field!") and return  
    else  
      @parameter = params[:search].downcase  
      @results = Event.all.where("lower(category) LIKE :search", search: @parameter)  
    end  
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def vote
    @event = Event.find(params[:id])
    @event.upvote_by current_register
    redirect_back fallback_location: root_path
  end
    
  def downvote
    @event = Event.find(params[:id])
    @event.downvote_by current_register
    redirect_back fallback_location: root_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :category, :description, :by ,:start, :end, :phone)
    end
    
   

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>I'm in</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand"><%= link_to "I AM IN", root_path %></div>
        <%= form_tag(search_page_path, :method => "get",   
          class: 'navbar-form navbar-left') do %>  
            <div class="input-group">  
              <%= search_field_tag :search, params[:search], placeholder: "Search(category)...", class: "form-control" %>  
            <div class="input-group-btn">  
              <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
            </div>  
            </div>  
          <% end %>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
          <% if current_register %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Post', new_event_path %></li>
              <li><%= link_to 'Account', account_path %></li>
              <li><%= link_to "Sign out", logout_path %></li>
              <li><%= link_to "Report user",new_report_path %></li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to "Sign Up", signup_path %></li>
              <li><%= link_to "Sign in", login_path %></li>
            </ul>
          <% end %>
        </nav>
      </div>
    </div>
  </header>

     <div id="main_content" class="container">
        <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>
        <div id="content" class="col-md-9 center-block">
            <%= yield %>
        </div>
      </div>


  </body>
</html>